# Generated by Django 3.0.3 on 2020-04-16 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200416_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='user_id',
            field=models.IntegerField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
