# Generated by Django 3.0.3 on 2020-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200416_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='field',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='takane',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
