# Generated by Django 3.0.3 on 2020-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200416_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='ability',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='takane_now',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
